# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[0,)" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="https://raw.githubusercontent.com/Cadiboo/NoCubes/master/update.json" #optional

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Cadiboo/NoCubes/issues" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://cadiboo.github.io/projects/nocubes" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="nocubes_logo.png" #optional

# A text field displayed in the mod UI
credits="The Forge and FML guys for Forge and FML and Cadiboo for making the mod" #optional

# A text field displayed in the mod UI
authors="Cadiboo, FellFromTheSky" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="nocubes" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory

# A display name for the mod
displayName="NoCubes (Reloaded)" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''

'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nocubes]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[15.24.0.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.nocubes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"

